/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MenuAdmController;
import java.awt.Toolkit;
import model.Utilitarios;

/**
 *
 * @author Th3Br
 */
public class AdmView extends javax.swing.JFrame {

    private final MenuAdmController controller;
    UsuarioPanel usuarioPane = new UsuarioPanel();
    PrincipalMenuPane menuPrincipal = new PrincipalMenuPane();
    ProdutoPane produtoPane = new ProdutoPane();
    ClientePane clientePane = new ClientePane();
    HistoricoPane historicoPane = new HistoricoPane();
    VendaPane vendaPane = new VendaPane();
    private String cpf;
    
    public AdmView() {
      
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(AdmView.MAXIMIZED_BOTH);//resolução do monitor
        
        MainPane.add(usuarioPane);
        MainPane.add(menuPrincipal);
        MainPane.add(produtoPane);
        MainPane.add(clientePane);
        MainPane.add(historicoPane);
        MainPane.add(vendaPane);
        
        controller = new MenuAdmController(this);
        controller.menuPrincipal();    
        Utilitarios u = new Utilitarios();
        u.InserirIcone(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoAbrirPaneUsuario = new javax.swing.JButton();
        CampoAbrirPaneProduto = new javax.swing.JButton();
        BotaoAbrirPaneClientes = new javax.swing.JButton();
        BotaoAbrirPaneHistorico = new javax.swing.JButton();
        BotaoAbrirPaneVenda = new javax.swing.JButton();
        MainPane = new javax.swing.JLayeredPane();
        BotaoAbrirPaneHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        BotaoAbrirPaneUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneUsuario.setText("Usuarios");
        BotaoAbrirPaneUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneUsuario);
        BotaoAbrirPaneUsuario.setBounds(45, 150, 150, 37);

        CampoAbrirPaneProduto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CampoAbrirPaneProduto.setText("Produtos");
        CampoAbrirPaneProduto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CampoAbrirPaneProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAbrirPaneProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoAbrirPaneProduto);
        CampoAbrirPaneProduto.setBounds(45, 205, 150, 37);

        BotaoAbrirPaneClientes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneClientes.setText("Clientes");
        BotaoAbrirPaneClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneClientesActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneClientes);
        BotaoAbrirPaneClientes.setBounds(45, 260, 150, 37);

        BotaoAbrirPaneHistorico.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneHistorico.setText("Histórico de vendas");
        BotaoAbrirPaneHistorico.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneHistorico);
        BotaoAbrirPaneHistorico.setBounds(45, 315, 150, 37);

        BotaoAbrirPaneVenda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneVenda.setText("Iniciar uma venda");
        BotaoAbrirPaneVenda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneVendaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneVenda);
        BotaoAbrirPaneVenda.setBounds(45, 95, 150, 37);

        MainPane.setLayout(new java.awt.CardLayout());
        getContentPane().add(MainPane);
        MainPane.setBounds(295, 40, 1570, 930);

        BotaoAbrirPaneHome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BotaoAbrirPaneHome.setText("Home");
        BotaoAbrirPaneHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BotaoAbrirPaneHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAbrirPaneHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAbrirPaneHome);
        BotaoAbrirPaneHome.setBounds(45, 40, 150, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    
    public ClientePane getClientePane() {
        return clientePane;
    }

    public void setClientePane(ClientePane clientePane) {
        this.clientePane = clientePane;
    }

    public UsuarioPanel getUsuarioPane() {
        return usuarioPane;
    }

    public void setUsuarioPane(UsuarioPanel usuarioPane) {
        this.usuarioPane = usuarioPane;
    }

    public PrincipalMenuPane getMenuPrincipal() {
        return menuPrincipal;
    }

    public void setMenuPrincipal(PrincipalMenuPane menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    public ProdutoPane getProdutoPane() {
        return produtoPane;
    }

    public void setProdutoPane(ProdutoPane produtoPane) {
        this.produtoPane = produtoPane;
    }
    
    public HistoricoPane getHistoricoPane() {
        return historicoPane;
    }

    public void setHistoricoPane(HistoricoPane HistoricoPane) {
        this.historicoPane = historicoPane;
    }
    
    public VendaPane getVendaPane() {
        return vendaPane;
    }

    public void setVendaPane(VendaPane vendaPane) {
        this.vendaPane = vendaPane;
    }

    private void BotaoAbrirPaneUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneUsuarioActionPerformed
        controller.usuarioPane();
    }//GEN-LAST:event_BotaoAbrirPaneUsuarioActionPerformed

    private void CampoAbrirPaneProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAbrirPaneProdutoActionPerformed
        controller.produtoPane();
    }//GEN-LAST:event_CampoAbrirPaneProdutoActionPerformed

    private void BotaoAbrirPaneHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneHomeActionPerformed
        controller.menuPrincipal();
    }//GEN-LAST:event_BotaoAbrirPaneHomeActionPerformed

    private void BotaoAbrirPaneClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneClientesActionPerformed
        controller.clientePane();
    }//GEN-LAST:event_BotaoAbrirPaneClientesActionPerformed

    private void BotaoAbrirPaneVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneVendaActionPerformed
        vendaPane.setCpf(this.cpf);
        controller.vendaPane();
    }//GEN-LAST:event_BotaoAbrirPaneVendaActionPerformed

    private void BotaoAbrirPaneHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAbrirPaneHistoricoActionPerformed
        controller.historicoPane();
    }//GEN-LAST:event_BotaoAbrirPaneHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmView().setVisible(true);
            }
        });
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAbrirPaneClientes;
    private javax.swing.JButton BotaoAbrirPaneHistorico;
    private javax.swing.JButton BotaoAbrirPaneHome;
    private javax.swing.JButton BotaoAbrirPaneUsuario;
    private javax.swing.JButton BotaoAbrirPaneVenda;
    private javax.swing.JButton CampoAbrirPaneProduto;
    private javax.swing.JLayeredPane MainPane;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

   
}