/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ClienteController;
import controller.EnderecoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Endereco;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Th3Br
 */
public class CadastroClienteView extends javax.swing.JFrame {
    
    private EnderecoController controllerEndereco;
    private ClienteController controller;
    private int estadoSelecionado = -1;
    private int cidadeSelecionada = -1;
    private int bairroSelecionado = -1;
    
    
    /**
     * Creates new form CadastrarCliente
     */
    public CadastroClienteView() {
        initComponents();
        this.setLocationRelativeTo(null); //Centraliza o frame na tela
        //this.controllerEndereco = new EnderecoController(this);
        AutoCompleteDecorator.decorate(ComboBoxEstado);
        AutoCompleteDecorator.decorate(ComboBoxCidade);
        AutoCompleteDecorator.decorate(ComboBoxBairro);
        AutoCompleteDecorator.decorate(ComboBoxLogradouro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoNomeCliente = new javax.swing.JTextField();
        CampoCpfCliente = new javax.swing.JTextField();
        CampoTelefoneCliente = new javax.swing.JTextField();
        CampoRgCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoCep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CampoNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CampoComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BotaoCadastro = new javax.swing.JButton();
        BotaoCancelarCadastro = new javax.swing.JButton();
        BotaoApagarCamposEndereco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoObservacaoCliente = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        ComboBoxEstado = new javax.swing.JComboBox();
        ComboBoxUF = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        ComboBoxCidade = new javax.swing.JComboBox();
        ComboBoxBairro = new javax.swing.JComboBox();
        ComboBoxLogradouro = new javax.swing.JComboBox();
        BotaoAtualizarCEP = new javax.swing.JButton();
        BotaoApagarCamposIndentificacaoCliente = new javax.swing.JButton();
        BotaoRadioEndereco = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CampoNomeCliente.setToolTipText("");
        CampoNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Cpf");

        jLabel3.setText("Telefone");

        jLabel5.setText("RG:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Dados de identificação do cliente:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Endereço:");

        CampoCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoCepFocusLost(evt);
            }
        });
        CampoCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCepActionPerformed(evt);
            }
        });

        jLabel6.setText("CEP:");

        jLabel8.setText("Logradouro:");

        jLabel9.setText("Bairro:");

        CampoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroActionPerformed(evt);
            }
        });

        jLabel10.setText("Numero:");

        jLabel11.setText("Complemento:");

        CampoComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoComplementoActionPerformed(evt);
            }
        });

        jLabel12.setText("Estado:");

        jLabel13.setText("Cidade:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setText("Cadastro de cliente");

        BotaoCadastro.setText("Cadastrar");
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });

        BotaoCancelarCadastro.setText("Cancelar");
        BotaoCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarCadastroActionPerformed(evt);
            }
        });

        BotaoApagarCamposEndereco.setText("Apagar campos");
        BotaoApagarCamposEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarCamposEnderecoActionPerformed(evt);
            }
        });

        CampoObservacaoCliente.setColumns(20);
        CampoObservacaoCliente.setRows(5);
        jScrollPane1.setViewportView(CampoObservacaoCliente);

        jLabel15.setText("Observação(ões):");

        ComboBoxEstado.setEditable(true);
        ComboBoxEstado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBoxEstadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBoxEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboBoxEstadoFocusLost(evt);
            }
        });
        ComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEstadoActionPerformed(evt);
            }
        });

        ComboBoxUF.setEditable(true);
        ComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxUFActionPerformed(evt);
            }
        });

        jLabel16.setText("UF:");

        ComboBoxCidade.setEditable(true);
        ComboBoxCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxCidadeItemStateChanged(evt);
            }
        });
        ComboBoxCidade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBoxCidadeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBoxCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ComboBoxCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboBoxCidadeFocusLost(evt);
            }
        });
        ComboBoxCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxCidadeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboBoxCidadeMousePressed(evt);
            }
        });
        ComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCidadeActionPerformed(evt);
            }
        });

        ComboBoxBairro.setEditable(true);
        ComboBoxBairro.setMaximumRowCount(100);
        ComboBoxBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxBairroMouseClicked(evt);
            }
        });
        ComboBoxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxBairroActionPerformed(evt);
            }
        });

        ComboBoxLogradouro.setEditable(true);
        ComboBoxLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLogradouroActionPerformed(evt);
            }
        });

        BotaoAtualizarCEP.setText("R");
        BotaoAtualizarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarCEPActionPerformed(evt);
            }
        });

        BotaoApagarCamposIndentificacaoCliente.setText("Apagar Campos");
        BotaoApagarCamposIndentificacaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarCamposIndentificacaoClienteActionPerformed(evt);
            }
        });

        BotaoRadioEndereco.setSelected(true);
        BotaoRadioEndereco.setText("Endereço");
        BotaoRadioEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRadioEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 624, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CampoNomeCliente)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(CampoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CampoNumero))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CampoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotaoAtualizarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16)
                                            .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel12)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CampoComplemento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(ComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxBairro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel13))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CampoTelefoneCliente)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel9)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BotaoApagarCamposIndentificacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BotaoApagarCamposEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BotaoCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(BotaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(90, 90, 90))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(BotaoRadioEndereco)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoApagarCamposIndentificacaoCliente))
                .addGap(65, 65, 65)
                .addComponent(BotaoRadioEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoAtualizarCEP)
                    .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoApagarCamposEndereco)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelarCadastro)
                    .addComponent(BotaoCadastro))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeClienteActionPerformed

    private void CampoCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCepActionPerformed
    
    }//GEN-LAST:event_CampoCepActionPerformed

    private void CampoComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoComplementoActionPerformed

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
        try {
            controller.realizarCadastro(BotaoRadioEndereco.isSelected());
        } catch (SQLException ex) {
            Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_BotaoCadastroActionPerformed

    private void BotaoCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoCancelarCadastroActionPerformed

    private void CampoCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoCepFocusLost

    }//GEN-LAST:event_CampoCepFocusLost

    private void BotaoApagarCamposEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarCamposEnderecoActionPerformed
        controller.apagarCamposCadastroEndereco();
        
    }//GEN-LAST:event_BotaoApagarCamposEnderecoActionPerformed

    private void ComboBoxEstadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBoxEstadoAncestorAdded
        try {
            controller.comboBoxEstadados();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboBoxEstadoAncestorAdded

    private void ComboBoxEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxEstadoFocusLost
         
    }//GEN-LAST:event_ComboBoxEstadoFocusLost

    private void ComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEstadoActionPerformed
        
        if(getComboBoxEstado().getSelectedIndex()>=0 && this.estadoSelecionado != getComboBoxEstado().getSelectedIndex() && getComboBoxEstado().getItemCount()>=26){
            this.estadoSelecionado = getComboBoxEstado().getSelectedIndex();    
            controller.atualizaComboBoxEstado();
            ComboBoxLogradouro.removeAllItems();
            this.cidadeSelecionada = -1;
            this.bairroSelecionado = -1;
            ComboBoxBairro.removeAllItems();
        }
    }//GEN-LAST:event_ComboBoxEstadoActionPerformed

    private void ComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxUFActionPerformed
        //Se tiver algo selecionado no combo box e ele for diferente do que ja tinha sido selecionado
        if(getComboBoxUF().getSelectedIndex()>=0 && this.estadoSelecionado != getComboBoxUF().getSelectedIndex() && getComboBoxUF().getItemCount()>=26){
            this.estadoSelecionado = getComboBoxUF().getSelectedIndex();
            controller.atualizaComboBoxEstado();
        }
    }//GEN-LAST:event_ComboBoxUFActionPerformed

    private void ComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCidadeActionPerformed

        if(this.cidadeSelecionada != getComboBoxCidade().getSelectedIndex() && getComboBoxCidade().getSelectedIndex()>=0){
            this.cidadeSelecionada = getComboBoxCidade().getSelectedIndex();
            try {
                controller.comboBoxBairros();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ComboBoxCidadeActionPerformed

    private void ComboBoxCidadeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBoxCidadeAncestorAdded

    }//GEN-LAST:event_ComboBoxCidadeAncestorAdded

    private void ComboBoxCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxCidadeFocusLost

    }//GEN-LAST:event_ComboBoxCidadeFocusLost

    private void ComboBoxCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxCidadeMouseClicked

    }//GEN-LAST:event_ComboBoxCidadeMouseClicked

    private void ComboBoxCidadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxCidadeMousePressed

    }//GEN-LAST:event_ComboBoxCidadeMousePressed

    private void ComboBoxCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBoxCidadeFocusGained

    }//GEN-LAST:event_ComboBoxCidadeFocusGained

    private void ComboBoxCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxCidadeItemStateChanged

    }//GEN-LAST:event_ComboBoxCidadeItemStateChanged

    private void ComboBoxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBairroActionPerformed
        if(this.bairroSelecionado != getComboBoxBairro().getSelectedIndex() && getComboBoxBairro().getSelectedIndex()>=0){
            this.bairroSelecionado = getComboBoxBairro().getSelectedIndex();
            try {
                controller.comboBoxLogradouros();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ComboBoxBairroActionPerformed

    private void ComboBoxBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxBairroMouseClicked

    }//GEN-LAST:event_ComboBoxBairroMouseClicked

    private void ComboBoxLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxLogradouroActionPerformed

    private void BotaoAtualizarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarCEPActionPerformed
        String cep = CampoCep.getText();
        String logradouro = (String) ComboBoxLogradouro.getSelectedItem();
        String cidade = (String) ComboBoxCidade.getSelectedItem();
        String uf = (String) ComboBoxUF.getSelectedItem();
        Endereco endereco = new Endereco(logradouro, cidade, uf);
        
        if (!cep.isEmpty()){
            try {
                controller.preencherCamposEndereco(cep);
            } catch (SQLException ex) {
                Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
           if(!logradouro.isEmpty() && !cidade.isEmpty() && !uf.isEmpty()){
               try {
                   controller.preencherCEP();
               } catch (SQLException ex) {
                   Logger.getLogger(CadastroClienteView.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
            else{
               //erro "CEP NÃO ENCONTRADO"
            }
        }
    }//GEN-LAST:event_BotaoAtualizarCEPActionPerformed

    private void CampoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroActionPerformed

    private void BotaoApagarCamposIndentificacaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarCamposIndentificacaoClienteActionPerformed
        controller.apagarCamposInformacaoCliente();
    }//GEN-LAST:event_BotaoApagarCamposIndentificacaoClienteActionPerformed

    private void BotaoRadioEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRadioEnderecoActionPerformed
        controller.enderecoHabilitado();
    }//GEN-LAST:event_BotaoRadioEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClienteView().setVisible(true);
            }
        });
    }

    public CadastroClienteView(JComboBox ComboBoxBairro, JComboBox ComboBoxCidade, JComboBox ComboBoxLogradouro, JTextField CampoNumero, JComboBox ComboBoxUF) {
        this.ComboBoxBairro = ComboBoxBairro;
        this.ComboBoxCidade = ComboBoxCidade;
        this.ComboBoxLogradouro = ComboBoxLogradouro;
        this.CampoNumero = CampoNumero;
        this.ComboBoxUF = ComboBoxUF;
    }

    
    public JTextField getCampoCpfCliente() {
        return CampoCpfCliente;
    }

    public void setCampoCpfCliente(JTextField CampoCpfCliente) {
        this.CampoCpfCliente = CampoCpfCliente;
    }

    public JTextField getCampoNomeCliente() {
        return CampoNomeCliente;
    }

    public void setCampoNomeCliente(JTextField CampoNomeCliente) {
        this.CampoNomeCliente = CampoNomeCliente;
    }

    public JTextField getCampoRgCliente() {
        return CampoRgCliente;
    }

    public void setCampoRgCliente(JTextField CampoRgCliente) {
        this.CampoRgCliente = CampoRgCliente;
    }

    public JTextField getCampoTelefoneCliente() {
        return CampoTelefoneCliente;
    }

    public void setCampoTelefoneCliente(JTextField CampoTelefoneCliente) {
        this.CampoTelefoneCliente = CampoTelefoneCliente;
    }
    
    public JComboBox getComboBoxEstado() {
        return ComboBoxEstado;
    }

    public JTextField getCampoComplemento() {
        return CampoComplemento;
    }

    public JRadioButton getBotaoRadioEndereco() {
        return BotaoRadioEndereco;
    }

    public void setBotaoRadioEndereco(JRadioButton BotaoRadioEndereco) {
        this.BotaoRadioEndereco = BotaoRadioEndereco;
    }

    public JButton getBotaoApagarCamposEndereco() {
        return BotaoApagarCamposEndereco;
    }

    public void setBotaoApagarCamposEndereco(JButton BotaoApagarCamposEndereco) {
        this.BotaoApagarCamposEndereco = BotaoApagarCamposEndereco;
    }

    public JButton getBotaoAtualizarCEP() {
        return BotaoAtualizarCEP;
    }

    public void setBotaoAtualizarCEP(JButton BotaoAtualizarCEP) {
        this.BotaoAtualizarCEP = BotaoAtualizarCEP;
    }

    public void setCampoComplemento(JTextField CampoComplemento) {
        this.CampoComplemento = CampoComplemento;
    }

    public JTextArea getCampoObservacaoCliente() {
        return CampoObservacaoCliente;
    }

    public void setCampoObservacaoCliente(JTextArea CampoObservacaoCliente) {
        this.CampoObservacaoCliente = CampoObservacaoCliente;
    }
    
    public void setComboBoxEstado(JComboBox ComboBoxEstado) {
        this.ComboBoxEstado = ComboBoxEstado;
    }

    public int getEstadoSelecionado() {
        return estadoSelecionado;
    }

    public ClienteController getController() {
        return controller;
    }

    public void setController(ClienteController controller) {
        this.controller = controller;
    }

    public void setEstadoSelecionado(int estadoSelecionado) {
        this.estadoSelecionado = estadoSelecionado;
    }

    public JComboBox getComboBoxUF() {
        return ComboBoxUF;
    }

    public void setComboBoxUF(JComboBox ComboBoxUF) {
        this.ComboBoxUF = ComboBoxUF;
    }

    public JComboBox getComboBoxBairro() {
        return ComboBoxBairro;
    }

    public void setComboBoxBairro(JComboBox ComboBoxBairro) {
        this.ComboBoxBairro = ComboBoxBairro;
    }

    public JComboBox getComboBoxCidade() {
        return ComboBoxCidade;
    }

    public void setComboBoxCidade(JComboBox ComboBoxCidade) {
        this.ComboBoxCidade = ComboBoxCidade;
    }

    public JComboBox getComboBoxLogradouro() {
        return ComboBoxLogradouro;
    }

    public void setComboBoxLogradouro(JComboBox ComboBoxLogradouro) {
        this.ComboBoxLogradouro = ComboBoxLogradouro;
    }

    public JTextField getCampoNumero() {
        return CampoNumero;
    }

    public void setCampoNumero(JTextField CampoNumero) {
        this.CampoNumero = CampoNumero;
    }

    public JTextField getCampoCep() {
        return CampoCep;
    }

    public void setCampoCep(JTextField CampoCep) {
        this.CampoCep = CampoCep;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoApagarCamposEndereco;
    private javax.swing.JButton BotaoApagarCamposIndentificacaoCliente;
    private javax.swing.JButton BotaoAtualizarCEP;
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JButton BotaoCancelarCadastro;
    private javax.swing.JRadioButton BotaoRadioEndereco;
    private javax.swing.JTextField CampoCep;
    private javax.swing.JTextField CampoComplemento;
    private javax.swing.JTextField CampoCpfCliente;
    private javax.swing.JTextField CampoNomeCliente;
    private javax.swing.JTextField CampoNumero;
    private javax.swing.JTextArea CampoObservacaoCliente;
    private javax.swing.JTextField CampoRgCliente;
    private javax.swing.JTextField CampoTelefoneCliente;
    private javax.swing.JComboBox ComboBoxBairro;
    private javax.swing.JComboBox ComboBoxCidade;
    private javax.swing.JComboBox ComboBoxEstado;
    private javax.swing.JComboBox ComboBoxLogradouro;
    private javax.swing.JComboBox ComboBoxUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
