/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.TextoController;
import controller.UsuarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author luizf
 */
public class UsuarioPanel extends javax.swing.JPanel {

    private final UsuarioController controller;
    private final TextoController controllerTexto;
    CadastroUsuarioView viewCadastrarUsuario = new CadastroUsuarioView();
    AtualizarUsuarioView viewAtualizarUsuario = new AtualizarUsuarioView();
    
    public UsuarioPanel() {
        initComponents();
        controller = new UsuarioController(this, viewCadastrarUsuario, viewAtualizarUsuario);//Construtor envia duas views, (UsuarioPanel e CadastroUsuarioView)
        controllerTexto = new TextoController();
        
        
        try { //Realiza a leitura da tabela
        controller.readTabelaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoCadastrarUsuario1 = new javax.swing.JButton();
        CampoPesquisaNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoPesquisaCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoPesquisaId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaUsuario = new javax.swing.JTable();
        BotaoAtualizarUsuario = new javax.swing.JButton();
        BotaoRemoverUsuario = new javax.swing.JButton();
        ComboBoxPesquisa = new javax.swing.JComboBox<>();
        BotaoApagarCampos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(673, 377));

        BotaoCadastrarUsuario1.setText("Cadastrar");
        BotaoCadastrarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarUsuario1ActionPerformed(evt);
            }
        });

        CampoPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaNomeActionPerformed(evt);
            }
        });
        CampoPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoPesquisaNomeKeyReleased(evt);
            }
        });

        jLabel1.setText("Nome:");

        CampoPesquisaCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoPesquisaCPFMouseClicked(evt);
            }
        });
        CampoPesquisaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaCPFActionPerformed(evt);
            }
        });
        CampoPesquisaCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoPesquisaCPFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoPesquisaCPFKeyTyped(evt);
            }
        });

        jLabel2.setText("CPF:");

        CampoPesquisaId.setEditable(false);
        CampoPesquisaId.setBackground(new java.awt.Color(220, 220, 220));
        CampoPesquisaId.setFocusable(false);
        CampoPesquisaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Id:");

        TabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Telefone", "Admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaUsuario);

        BotaoAtualizarUsuario.setText("Atualizar");
        BotaoAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarUsuarioActionPerformed(evt);
            }
        });

        BotaoRemoverUsuario.setText("Remover");
        BotaoRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverUsuarioActionPerformed(evt);
            }
        });

        ComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Usuário", "Admin" }));
        ComboBoxPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxPesquisaMouseClicked(evt);
            }
        });
        ComboBoxPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPesquisaActionPerformed(evt);
            }
        });

        BotaoApagarCampos.setText("Apagar Campos");
        BotaoApagarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addGap(129, 129, 129))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CampoPesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addGap(114, 114, 114))
                                    .addComponent(CampoPesquisaNome)
                                    .addComponent(BotaoApagarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(258, 258, 258)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addGap(172, 172, 172))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CampoPesquisaCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(ComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoCadastrarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoAtualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoPesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoApagarCampos)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoAtualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoCadastrarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarUsuario1ActionPerformed
        //seta o controller do view cadastro e torna ele visivel
        viewCadastrarUsuario.setController(controller);
        controller.apagarCamposCadastro();// Antes de ser visivel ele apaga os campos do cadastro
        viewCadastrarUsuario.setLocationRelativeTo(null);
        viewCadastrarUsuario.setVisible(true); 
    }//GEN-LAST:event_BotaoCadastrarUsuario1ActionPerformed

    public JTextField getCampoPesquisaCPF() {
        return CampoPesquisaCPF;
    }

    public void setCampoPesquisaCPF(JTextField CampoPesquisaCPF) {
        this.CampoPesquisaCPF = CampoPesquisaCPF;
    }

    public JTextField getCampoPesquisaId() {
        return CampoPesquisaId;
    }

    public void setCampoPesquisaId(JTextField CampoPesquisaId) {
        this.CampoPesquisaId = CampoPesquisaId;
    }

    public JTextField getCampoPesquisaNome() {
        return CampoPesquisaNome;
    }

    public void setCampoPesquisaNome(JTextField CampoPesquisaNome) {
        this.CampoPesquisaNome = CampoPesquisaNome;
    }

    public JTable getTabelaUsuario() {
        return TabelaUsuario;
    }

    public void setTabelaUsuario(JTable TabelaUsuario) {
        this.TabelaUsuario = TabelaUsuario;
    }

    public JComboBox<String> getComboBoxPesquisa() {
        return ComboBoxPesquisa;
    }

    public void setComboBoxPesquisa(JComboBox<String> ComboBoxPesquisa) {
        this.ComboBoxPesquisa = ComboBoxPesquisa;
    }

    private void CampoPesquisaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaCPFActionPerformed
    
    }//GEN-LAST:event_CampoPesquisaCPFActionPerformed

    private void CampoPesquisaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaIdActionPerformed

    private void TabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuarioMouseClicked
        //Preencher campos com os dados da linha
        if(TabelaUsuario.getSelectedRow() != -1){
            CampoPesquisaId.setText(TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_TabelaUsuarioMouseClicked

    private void BotaoAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarUsuarioActionPerformed
        //Verifica se tem alguma linha selecionada
        if(getTabelaUsuario().getSelectedRow()!=-1){
            viewAtualizarUsuario.setController(this.controller);
            viewAtualizarUsuario.setLocationRelativeTo(null);//Centraliza
            viewAtualizarUsuario.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nenhum usuário selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotaoAtualizarUsuarioActionPerformed

    private void BotaoRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverUsuarioActionPerformed
         
        if(getTabelaUsuario().getSelectedRow()!=-1){
            try {
                controller.removerUsuario();
            } catch (SQLException ex) {
                Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum usuário selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
     
    }//GEN-LAST:event_BotaoRemoverUsuarioActionPerformed

    private void ComboBoxPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPesquisaActionPerformed
        try {
            controller.buscarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboBoxPesquisaActionPerformed

    private void BotaoApagarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarCamposActionPerformed
        controller.apagarCampos();
        try {
            controller.readTabelaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoApagarCamposActionPerformed

    private void CampoPesquisaCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPesquisaCPFKeyTyped
      //Verifica validação da escrita no campo do cpf
      if(controllerTexto.formatacaoCPF(evt, getCampoPesquisaCPF().getText())){
         CampoPesquisaCPF.setText(controllerTexto.mascaraCPF(getCampoPesquisaCPF().getText()));
      }
      else{
          evt.consume();//Consome a letra e evita ela aparecer no campo do texto.
      }
    }//GEN-LAST:event_CampoPesquisaCPFKeyTyped

    private void CampoPesquisaCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoPesquisaCPFMouseClicked

    }//GEN-LAST:event_CampoPesquisaCPFMouseClicked

    private void CampoPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaNomeActionPerformed

    private void CampoPesquisaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPesquisaNomeKeyReleased
        try {
            controller.buscarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CampoPesquisaNomeKeyReleased

    private void CampoPesquisaCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPesquisaCPFKeyReleased
        try {
            controller.buscarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CampoPesquisaCPFKeyReleased

    private void ComboBoxPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxPesquisaMouseClicked

    }//GEN-LAST:event_ComboBoxPesquisaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoApagarCampos;
    private javax.swing.JButton BotaoAtualizarUsuario;
    private javax.swing.JButton BotaoCadastrarUsuario1;
    private javax.swing.JButton BotaoRemoverUsuario;
    private javax.swing.JTextField CampoPesquisaCPF;
    private javax.swing.JTextField CampoPesquisaId;
    private javax.swing.JTextField CampoPesquisaNome;
    private javax.swing.JComboBox<String> ComboBoxPesquisa;
    private javax.swing.JTable TabelaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
