/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.sun.source.doctree.IdentifierTree;
import controller.TabelaController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author luizf
 */
public class UsuarioPanel extends javax.swing.JPanel {

    private final TabelaController controller;
    
    public UsuarioPanel() {
        initComponents();
        controller = new TabelaController(this);
        
        try {
        controller.readTabelaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoCadastrarUsuario1 = new javax.swing.JButton();
        CampoPesquisaNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoPesquisaCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoPesquisaId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaUsuario = new javax.swing.JTable();
        CheckAdmin = new javax.swing.JCheckBox();
        BotaoAtualizarUsuario = new javax.swing.JButton();
        CampoPesquisaTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotaoAtualizarTabela = new javax.swing.JButton();
        BotaoRemoverUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(673, 377));

        BotaoCadastrarUsuario1.setText("Cadastrar");
        BotaoCadastrarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarUsuario1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        CampoPesquisaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaCPFActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        CampoPesquisaId.setEditable(false);
        CampoPesquisaId.setBackground(new java.awt.Color(220, 220, 220));
        CampoPesquisaId.setFocusable(false);
        CampoPesquisaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Id:");

        TabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Telefone", "Admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaUsuario);

        CheckAdmin.setText("Admin");

        BotaoAtualizarUsuario.setText("Atualizar");
        BotaoAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarUsuarioActionPerformed(evt);
            }
        });

        CampoPesquisaTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaTelefoneActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone:");

        BotaoAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtualizarTabelaActionPerformed(evt);
            }
        });

        BotaoRemoverUsuario.setText("Remover");
        BotaoRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoCadastrarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoAtualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addGap(129, 129, 129))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoPesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addGap(114, 114, 114))
                            .addComponent(CampoPesquisaNome))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addGap(126, 126, 126))
                            .addComponent(CampoPesquisaTelefone))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addGap(126, 126, 126))
                            .addComponent(CampoPesquisaCPF))
                        .addGap(65, 65, 65)
                        .addComponent(CheckAdmin)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoPesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckAdmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoPesquisaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoCadastrarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoAtualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarUsuario1ActionPerformed
        CadastroUsuarioView view = new CadastroUsuarioView();
        view.setVisible(true);
    }//GEN-LAST:event_BotaoCadastrarUsuario1ActionPerformed

    public JTextField getCampoPesquisaCPF() {
        return CampoPesquisaCPF;
    }

    public void setCampoPesquisaCPF(JTextField CampoPesquisaCPF) {
        this.CampoPesquisaCPF = CampoPesquisaCPF;
    }

    public JTextField getCampoPesquisaId() {
        return CampoPesquisaId;
    }

    public void setCampoPesquisaId(JTextField CampoPesquisaId) {
        this.CampoPesquisaId = CampoPesquisaId;
    }

    public JTextField getCampoPesquisaNome() {
        return CampoPesquisaNome;
    }

    public void setCampoPesquisaNome(JTextField CampoPesquisaNome) {
        this.CampoPesquisaNome = CampoPesquisaNome;
    }

    public JCheckBox getCheckAdmin() {
        return CheckAdmin;
    }

    public void setCheckAdmin(JCheckBox CheckAdmin) {
        this.CheckAdmin = CheckAdmin;
    }

    public JTextField getCampoPesquisaTelefone() {
        return CampoPesquisaTelefone;
    }

    public void setCampoPesquisaTelefone(JTextField CampoPesquisaTelefone) {
        this.CampoPesquisaTelefone = CampoPesquisaTelefone;
    }

    public JTable getTabelaUsuario() {
        return TabelaUsuario;
    }

    public void setTabelaUsuario(JTable TabelaUsuario) {
        this.TabelaUsuario = TabelaUsuario;
    }

    private void CampoPesquisaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaCPFActionPerformed

    private void CampoPesquisaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaIdActionPerformed

    private void TabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuarioMouseClicked
        //Preencher campos com os dados da linha
        if(TabelaUsuario.getSelectedRow() != -1){
            CampoPesquisaId.setText(TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(), 0).toString());
            CampoPesquisaNome.setText(TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(), 1).toString());
            CampoPesquisaCPF.setText(TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(), 2).toString());   
            CampoPesquisaTelefone.setText(TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(), 3).toString());
            CheckAdmin.setSelected((boolean) TabelaUsuario.getValueAt(TabelaUsuario.getSelectedRow(), 4));
            
        }
    }//GEN-LAST:event_TabelaUsuarioMouseClicked

    private void BotaoAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarUsuarioActionPerformed

    }//GEN-LAST:event_BotaoAtualizarUsuarioActionPerformed

    private void CampoPesquisaTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaTelefoneActionPerformed

    private void BotaoAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtualizarTabelaActionPerformed
        try {
            controller.apagarCampos();
            controller.readTabelaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoAtualizarTabelaActionPerformed

    private void BotaoRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverUsuarioActionPerformed
        if(CampoPesquisaId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum usuário selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{    
            try {
                controller.removerUsuario();
            } catch (SQLException ex) {
                Logger.getLogger(UsuarioPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     
    }//GEN-LAST:event_BotaoRemoverUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtualizarTabela;
    private javax.swing.JButton BotaoAtualizarUsuario;
    private javax.swing.JButton BotaoCadastrarUsuario1;
    private javax.swing.JButton BotaoRemoverUsuario;
    private javax.swing.JTextField CampoPesquisaCPF;
    private javax.swing.JTextField CampoPesquisaId;
    private javax.swing.JTextField CampoPesquisaNome;
    private javax.swing.JTextField CampoPesquisaTelefone;
    private javax.swing.JCheckBox CheckAdmin;
    private javax.swing.JTable TabelaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
